[package]
name = "Image-Importer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.16"
tracing = "0.1.29"
tracing-subscriber = "0.3.3"
rusb = "0.9.0"